package:
  name: yank-dev
  version: !!str 0.0.0

source:
  path: ../..

build:
  preserve_egg_dir: True
  number: 0
  skip: True # [py2k]

requirements:
  build:
    - python
    - cython
    - setuptools

  run:
    - python
    - pandas
    - numpy >=1.11
    - scipy
    - cython
    - netcdf4 ==1.3.1  # TODO: Fix this right after bugfix: "always return masked array by default, even if there are no masked values"
    - openmm >=7.1
    - mdtraj >=1.7.2
    - openmmtools >=0.15.0
    - pymbar
    - ambermini >=16.16.0
    - docopt
    - openmoltools >=0.7.5
    - mpi4py
    - pyyaml
    - clusterutils
    - sphinxcontrib-bibtex
    - cerberus ==1.1.*
    - matplotlib
    - jupyter
    - pdbfixer
    - libnetcdf >=4.6.0
    - msmbuilder

test:
  requires:
    - nose
    - nose-timer
  imports:
    - yank
  commands:
    - yank --help

about:
  home: https://github.com/choderalab/yank
  license: MIT License
