package:
  name: yank-dev
  version: !!str 0.0.0

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - netcdf4
    - openmm
    - openmmtools
    - pymbar ==2.1.0b0
    - ambermini
    - docopt
    - openmoltools
    - jinja2
    - sphinxcontrib-bibtex

  run:
    - python
    - pandas
    - numpy
    - scipy
    - cython
    - netcdf4
    - openmm
    - openmmtools
    - pymbar ==2.1.0b0
    - ambermini
    - docopt
    - openmoltools
    - mpi4py
    - pyyaml
    - jinja2
    - clusterutils
    - sphinxcontrib-bibtex

test:
  requires:
    - nose
  imports:
    - yank
  commands:
    - nosetests yank --nocapture --verbosity=2 --with-doctest -a '!slow' --processes=2 --process-timeout=500
    - which yank
    - yank --help

about:
  home: https://github.com/choderalab/yank
  license: GNU Lesser General Public License v2 or later (LGPLv2+)




