package:
  name: yank-dev
  version: !!str 0.0.0

source:
  path: ../..

build:
  preserve_egg_dir: True
  number: 0
  skip: True # [py2k]

requirements:
  build:
    - python
    - cython
    - setuptools
    #- gcc 4.8.2 # [linux]
    #- gcc 4.8.2 # [osx]

  run:
    - python
    - pandas
    - numpy >=1.11
    - scipy
    - cython
    - netcdf4
    - openmm >=7.1
    - mdtraj >=1.7.2
    - openmmtools >=0.14.0
    - pymbar
    - ambermini >=16.16.0
    - docopt
    - openmoltools >=0.7.5
    - mpi4py
    - pyyaml
    - clusterutils
    - sphinxcontrib-bibtex
    - cerberus
    - matplotlib
    - jupyter
    - pdbfixer
    - libnetcdf >=4.6.0
    #- libgcc

test:
  requires:
    - nose
    - nose-timer
  imports:
    - yank
  commands:
    - yank --help

about:
  home: https://github.com/choderalab/yank
  license: MIT License
